// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqXqMZEAu9bPmgxikZqhsLUP8RIQox5-c',
    appId: '1:699390760154:web:a2abc389cee33b1b67c1e3',
    messagingSenderId: '699390760154',
    projectId: 'ap1-coach',
    authDomain: 'ap1-coach.firebaseapp.com',
    storageBucket: 'ap1-coach.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT4pzGZDCo70CcDBnBAYEvh5WSDoAryY0',
    appId: '1:699390760154:android:0f413cf27167a44467c1e3',
    messagingSenderId: '699390760154',
    projectId: 'ap1-coach',
    storageBucket: 'ap1-coach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtdeKAiyOvAndH3LZogyhlBBvv0BgqjAg',
    appId: '1:699390760154:ios:c198e63bfc1bef0767c1e3',
    messagingSenderId: '699390760154',
    projectId: 'ap1-coach',
    storageBucket: 'ap1-coach.firebasestorage.app',
    iosBundleId: 'com.example.nasa',
  );
}
